sudo: required
dist: trusty
language: node_js
notifications:
  email: false
node_js:
  - "6"

env:
  - ANGULAR_VERSION=1.3.20
  - ANGULAR_VERSION=1.4.14
  - ANGULAR_VERSION=1.5.11
  - ANGULAR_VERSION=1.6.5

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  - npm install -g json
  - json -I -f package.json -e 'this.dependencies.angular="'$ANGULAR_VERSION'"'
  - json -I -f bower.json -e 'this.dependencies.angular="'$ANGULAR_VERSION'"'

before_script:
  - grunt connect:test:keepalive &
  - npm install -g bower
  - bower install

script:
  - npm test
